export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-light': 'var(--color-primary-light)',
        secondary: 'var(--color-secondary)',
        surface: 'var(--color-surface)',
        'text-secondary': 'var(--color-text-secondary)',
        border: 'var(--color-border)',
        'border-light': 'var(--color-border-light)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        danger: 'var(--color-danger)',
        info: 'var(--color-info)',
        orange: 'var(--color-orange)',
        blue: 'var(--color-blue)',
        purple: 'var(--color-purple)',
        teal: 'var(--color-teal)',
        yellow: 'var(--color-yellow)',
        leads: 'var(--color-leads)',
        opportunities: 'var(--color-opportunities)',
        quotes: 'var(--color-quotes)',
        accounts: 'var(--color-accounts)',
        documents: 'var(--color-documents)',
        meetings: 'var(--color-meetings)',
        calls: 'var(--color-calls)',
        calendar: 'var(--color-calendar)',
        tasks: 'var(--color-tasks)',
        'project-costing': 'var(--color-project-costing)',
        cases: 'var(--color-cases)',
        vendors: 'var(--color-vendors)',
        emails: 'var(--color-emails)',
        billing: 'var(--color-billing)',
      },
      borderRadius: {
        'card': '18px',
        'button': '14px',
        'input': '14px',
        'container': '24px',
      },
      boxShadow: {
        'soft': '0 4px 15px rgba(0,0,0,0.05)',
        'soft-lg': '0 8px 30px rgba(0,0,0,0.05)',
      },
      fontFamily: {
        'heading': ['Plus Jakarta Sans', 'sans-serif'],
        'body': ['Plus Jakarta Sans', 'sans-serif'],
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
      },
    },
  },
  plugins: [],
}
