"""Add advanced POV fields to subjects

Revision ID: 266413a06b3d
Revises: 404b27333461
Create Date: 2026-06-10 11:50:15.392131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '266413a06b3d'
down_revision: Union[str, None] = '404b27333461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate erroneously emitted a drop of school_settings here
    # (the SchoolSetting model was not registered in env.py target_metadata at
    # generation time, so alembic saw the table as orphaned). Removed so the
    # table created in f747a6e0cc72 survives — /admin/settings needs it.
    op.add_column('academic_subjects', sa.Column('credit_hours', sa.Integer(), nullable=True))
    op.add_column('academic_subjects', sa.Column('lab_fee_amount', sa.Integer(), nullable=True))
    op.add_column('academic_subjects', sa.Column('grading_scheme_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'academic_subjects', 'grading_schemes', ['grading_scheme_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_academic_years_is_active', table_name='academic_years')
    op.drop_index('one_active_year', table_name='academic_years', postgresql_where='(is_active = true)')
    op.alter_column('audit_logs', 'old_values',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_values',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_foreign_key(None, 'audit_logs', 'users', ['changed_by'], ['id'])
    op.drop_constraint('holidays_date_key', 'holidays', type_='unique')
    op.drop_index('ix_holidays_date', table_name='holidays')
    op.create_index(op.f('ix_holidays_date'), 'holidays', ['date'], unique=True)
    op.drop_constraint('payroll_runs_run_id_key', 'payroll_runs', type_='unique')
    op.create_unique_constraint('uq_payroll_run_id', 'payroll_runs', ['run_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payroll_run_id', 'payroll_runs', type_='unique')
    op.create_unique_constraint('payroll_runs_run_id_key', 'payroll_runs', ['run_id'])
    op.drop_index(op.f('ix_holidays_date'), table_name='holidays')
    op.create_index('ix_holidays_date', 'holidays', ['date'], unique=False)
    op.create_unique_constraint('holidays_date_key', 'holidays', ['date'])
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.alter_column('audit_logs', 'new_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('one_active_year', 'academic_years', ['is_active'], unique=True, postgresql_where='(is_active = true)')
    op.create_index('ix_academic_years_is_active', 'academic_years', ['is_active'], unique=False)
    op.drop_constraint(None, 'academic_subjects', type_='foreignkey')
    op.drop_column('academic_subjects', 'grading_scheme_id')
    op.drop_column('academic_subjects', 'lab_fee_amount')
    op.drop_column('academic_subjects', 'credit_hours')
    # NOTE: matching removal — upgrade no longer drops school_settings, so the
    # downgrade must not re-create it.
    # ### end Alembic commands ###
