"""Add department, description, and is_active to Subject

Revision ID: 404b27333461
Revises: 20260610
Create Date: 2026-06-10 11:18:13.193279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '404b27333461'
down_revision: Union[str, None] = '20260610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_subjects', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('academic_subjects', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('academic_subjects', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic_subjects', 'is_active')
    op.drop_column('academic_subjects', 'description')
    op.drop_column('academic_subjects', 'department')
    # ### end Alembic commands ###
