"""Add unique constraint to class_subjects

Revision ID: e3af894aede7
Revises: 266413a06b3d
Create Date: 2026-06-10 12:06:48.188010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3af894aede7'
down_revision: Union[str, None] = '266413a06b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_class_subject', 'class_subjects', ['class_id', 'subject_id'])
    op.drop_constraint('class_subjects_class_id_fkey', 'class_subjects', type_='foreignkey')
    op.drop_constraint('class_subjects_subject_id_fkey', 'class_subjects', type_='foreignkey')
    op.create_foreign_key(None, 'class_subjects', 'academic_classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'class_subjects', 'academic_subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'class_subjects', type_='foreignkey')
    op.drop_constraint(None, 'class_subjects', type_='foreignkey')
    op.create_foreign_key('class_subjects_subject_id_fkey', 'class_subjects', 'academic_subjects', ['subject_id'], ['id'])
    op.create_foreign_key('class_subjects_class_id_fkey', 'class_subjects', 'academic_classes', ['class_id'], ['id'])
    op.drop_constraint('uq_class_subject', 'class_subjects', type_='unique')
    # ### end Alembic commands ###
